server:
  port: 8081

spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/auth_db
    username: root
    password: admin
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.r2dbc: DEBUG