version: '3.8'

services:
  # MySQL Databases
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    networks:
      - mascotas-network

  mysql-pet:
    image: mysql:8.0
    container_name: mysql-pet
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pet_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_pet_data:/var/lib/mysql
    networks:
      - mascotas-network

  # Discovery Service
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - mysql-auth
      - mysql-pet
    networks:
      - mascotas-network
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql-auth:3306/auth_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=admin

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - mysql-auth
    networks:
      - mascotas-network
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql-auth:3306/auth_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  # Pet Service
  pet-service:
    build:
      context: ./pet-service
      dockerfile: Dockerfile
    container_name: pet-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - mysql-pet
    networks:
      - mascotas-network
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql-pet:3306/pet_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  # Dashboard Service
  dashboard-service:
    build:
      context: ./dashboard-service
      dockerfile: Dockerfile
    container_name: dashboard-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - pet-service
    networks:
      - mascotas-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - auth-service
      - pet-service
      - dashboard-service
    networks:
      - mascotas-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

volumes:
  mysql_auth_data:
  mysql_pet_data:

networks:
  mascotas-network:
    driver: bridge